AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TwoThirds backend with Lambda functions and DynamoDB

Resources:

  TwoThirdsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TwoThirdsGuesses
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SubmitGuessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.submitGuess
      Runtime: nodejs14.x
      Environment:
        Variables:
          GUESSES_TABLE_NAME: !Ref TwoThirdsTable
      Events:
        SubmitGuess:
          Type: Api
          Properties:
            Path: /submit-guess
            Method: post

  GetLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.getLeaderboard
      Runtime: nodejs14.x
      Environment:
        Variables:
          GUESSES_TABLE_NAME: !Ref TwoThirdsTable
      Events:
        GetLeaderboard:
          Type: Api
          Properties:
            Path: /leaderboard
            Method: get

  GetPreviousResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.getPreviousResults
      Runtime: nodejs14.x
      Environment:
        Variables:
          GUESSES_TABLE_NAME: !Ref TwoThirdsTable
      Events:
        GetPreviousResults:
          Type: Api
          Properties:
            Path: /previous-results
            Method: get
